[tools]
python = "3.12"
uv = "latest"

# Hook that runs after tools are installed
[hooks]
postinstall = "mise run _setup"

# Hidden helper tasks
[tasks._setup]
hide = true
run = "python scripts/setup.py"

[tasks._start-mock]
hide = true
dir = "mock_server"
env = { COMPOSE_PROJECT_NAME = "vista-mock" }
run = ["docker-compose up -d", "python ../scripts/check_mock_server.py"]

[tasks.stop-mock]
description = "Stop the mock server"
dir = "mock_server"
env = { COMPOSE_PROJECT_NAME = "vista-mock" }
run = ["docker-compose down", "echo '✅ Mock server stopped'"]

[tasks.dev-with-mock]
description = "Start development with mock server (handles all setup)"
run = [
    # Auto-setup if needed
    "python scripts/silent_setup.py",
    # Start mock server if needed
    "python scripts/start_mock_if_needed.py",
    # Run MCP server with dev inspector
    "uv run mcp dev server.py:server"
]

[tasks.dev]
description = "Start development server"
run = [
    # Auto-setup if needed
    "python scripts/silent_setup.py",
    # Run MCP server
    "echo '🏃 Starting MCP server...'",
    "uv run mcp dev server.py:server"
]

# Utility tasks (optional)
[tasks.test]
description = "Run tests"
run = "uv run pytest"

[tasks.lint]
description = "Check code quality (format + lint)"
run = ["uv run black src/", "uv run ruff check src/"]

[tasks.logs]
description = "View mock server logs"
dir = "mock_server"
env = { COMPOSE_PROJECT_NAME = "vista-mock" }
run = "docker-compose logs -f"

[tasks.setup-claude]
description = "Set up Claude Desktop configuration"
run = "python scripts/setup_claude_desktop.py"

[tasks.dev-sse]
description = "Start SSE server for development"
env = { VISTA_MCP_TRANSPORT = "sse" }
run = [
    # Auto-setup if needed
    "python scripts/silent_setup.py",
    # Run SSE server
    "echo '🌐 Starting SSE server...'",
    "echo '📍 SSE endpoint: http://localhost:8000/sse'",
    "echo '📝 Message endpoint: http://localhost:8000/messages/'",
    "echo ''",
    "echo '🔧 Configure your client with:'",
    "echo '  {\"url\": \"http://localhost:8000/sse\"}'",
    "echo ''",
    "uv run python http_server.py"
]

[tasks.dev-sse-with-mock]
description = "Start SSE server with mock Vista API"
env = { VISTA_MCP_TRANSPORT = "sse" }
run = [
    # Auto-setup if needed
    "python scripts/silent_setup.py",
    # Start mock server if needed
    "python scripts/start_mock_if_needed.py",
    # Run SSE server
    "echo '🌐 Starting SSE server with mock...'",
    "echo '📍 SSE endpoint: http://localhost:8000/sse'",
    "echo '📝 Message endpoint: http://localhost:8000/messages/'",
    "echo ''",
    "echo '🔧 Configure your client with:'",
    "echo '  {\"url\": \"http://localhost:8000/sse\"}'",
    "echo ''",
    "uv run python http_server.py"
]