version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no
  
  uvicorn.error:
    level: INFO
    handlers: [console, error_file]
    propagate: no
  
  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: no
  
  src:
    level: DEBUG
    handlers: [console, error_file]
    propagate: no

root:
  level: INFO
  handlers: [console]